set ai

syntax on

set expandtab
set tabstop=4
set shiftwidth=4
set nobackup
set incsearch
set hlsearch

set cino=:0

set background=dark

au Bufread,BufNewFile *.tie,*.tpp setf tie
au Bufread,BufNewFile Makefile set noexpandtab

set clipboard=exclude:.*

set ruler

" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif
